// =============================================================================
// AR Training — Shared Types
// Single source of truth for all TypeScript DTOs that cross container boundaries.
// Used by: client/, app/, feedback/
//
// Python equivalent: evaluation/src/interfaces.py
// Wire format reference: docs/API_CONTRACT.md
// =============================================================================

// ─── Primitives ───────────────────────────────────────────────────────────────

/** A single landmark point in normalized image coordinates (0..1). */
export interface Landmark {
    x: number;
    y: number;
    z: number;
    /** Confidence that the landmark is visible. May be absent for some models. */
    visibility: number;
}

/** Unique identifier for a clip's analysis window. One window is produced per clip. Format: `"{session_id}:{clip_sequence}"` */
export type WindowID = string;

/**
 * A matrix of Mel-frequency cepstral coefficients.
 * Rows are time frames, columns are the 13 MFCC coefficients (Meyda default).
 * Shape: [n_frames][13]
 */
export type MfccMatrix = number[][];

// ─── Client → Server (WebSocket) ─────────────────────────────────────────────

/**
 * One frame of landmark data extracted from the webcam by MediaPipe.js.
 * Sent continuously over WebSocket while a session is active.
 *
 * `face_landmarks` contains 478 points. Hand arrays contain 21 points each,
 * or are empty if the hand is not detected in the frame.
 */
export interface VideoFrame {
    type: "video_frame";
    session_id: string;
    /** Monotonically increasing counter, reset to 0 at session start. */
    frame_id: number;
    /** Seconds elapsed since session start. */
    timestamp: number;
    /** 478 MediaPipe face mesh landmarks in normalized image coordinates. */
    face_landmarks: Landmark[];
    /** 21 hand landmarks, or empty array if left hand is not detected. */
    left_hand: Landmark[];
    /** 21 hand landmarks, or empty array if right hand is not detected. */
    right_hand: Landmark[];
}

/**
 * One chunk of audio data from the microphone, covering approximately 2 seconds.
 *
 * Contains both raw PCM (for Whisper transcription server-side) and pre-computed
 * MFCCs (for the behavior classifier). Sending both avoids duplicating the
 * bandwidth cost — raw audio is ~64KB per chunk, MFCCs are ~3KB.
 */
export interface AudioChunk {
    type: "audio_chunk";
    session_id: string;
    /** Monotonically increasing counter, reset to 0 at session start. */
    chunk_id: number;
    /** Seconds elapsed since session start. */
    timestamp: number;
    /** Base64-encoded raw s16le PCM bytes, resampled to `sample_rate`. */
    pcm: string;
    /** Always 16000 Hz — required by Whisper. */
    sample_rate: number;
    /** `[n_frames][13]` MFCCs pre-computed client-side via Meyda.js. */
    mfccs: MfccMatrix;
}

/**
 * Sent by the client when a scenario clip finishes playing.
 *
 * The App container uses this to:
 *   1. Signal the ClipSession to flush and finalise the transcript
 *   2. Await the resolved AnalysisWindow and dispatch it to Evaluation
 *   3. Resolve the next clip from branch_conditions using the returned escalation_score
 *   4. Append a ConversationTurn to the session history
 *   5. Transition ACTIVE → PAUSED → ACTIVE (or COMPLETED if terminal)
 *
 * The client must stop sending VideoFrame and AudioChunk messages after
 * sending this and wait for a ClipReady or SessionComplete response.
 */
export interface ClipEnded {
    type: "clip_ended";
    session_id: string;
    clip_id: string;
}

export type ClientMessage = VideoFrame | AudioChunk | ClipEnded;

// ─── Server → Client (WebSocket) ─────────────────────────────────────────────

/**
 * Sent by the App container when a transcript segment arrives from the
 * Transcription container during a clip.
 *
 * Carries the accumulated transcript for the current clip so far.
 * Intended for development and debugging — the client may choose not to
 * display this to students in production.
 *
 * `queue_position` is non-null only while the session is in the QUEUED state.
 */
export interface SessionUpdate {
    type: "session_update";
    session_id: string;
    /** Accumulated transcript for the current clip so far. */
    transcript: string;
    /** Position in the waiting queue, or null if the session is active. */
    queue_position: number | null;
}


/**
 * Sent once at the end of a session when feedback generation is complete.
 * Delivered over the still-open WebSocket after the terminal clip is reached.
 */
export interface SessionComplete {
    type: "session_complete";
    session_id: string;
    /** Full debrief advice generated by the LLM. */
    advice: string;
    severity: "low" | "medium" | "high";
    /** Notable moments from the session, e.g. `"Turn 2: voice tension spiked"`. */
    highlights: string[];
}

/**
 * Streamed token-by-token from the Feedback container while advice is being
 * generated. Arrives before `SessionComplete`.
 */
export interface FeedbackToken {
    type: "feedback_token";
    session_id: string;
    token: string;
}

/** Sent by the App container when a recoverable or fatal error occurs. */
export interface ServerError {
    type: "error";
    session_id: string;
    /** Machine-readable error code, e.g. `"session_expired"`, `"invalid_frame"`. */
    code: string;
    message: string;
}

/**
 * Sent by the App container after processing a ClipEnded message.
 * Tells the client which clip to load and play next.
 *
 * When next_clip_id is null the scenario is complete — the client should
 * wait for FeedbackToken and SessionComplete messages.
 */
export interface ClipReady {
    type: "clip_ready";
    session_id: string;
    /** The clip the client should load and begin playing. Null if terminal. */
    next_clip_id: string | null;
    /** The escalation_score that drove this branching decision. */
    clip_score: number;
}

export type ServerMessage = SessionUpdate | SessionComplete | FeedbackToken | ServerError | ClipReady;

// ─── HTTP — Session management ────────────────────────────────────────────────

export interface CreateSessionRequest {
    user_id: string;
    scenario_id: string;
    /** ISO 639-1 language code, e.g. `"nl"`. */
    language: string;
}

/**
 * Returned by `POST /session/create`.
 *
 * When `state` is `"queued"` the server is at capacity. The client should
 * poll `GET /session/{id}/queue` until `state` becomes `"active"`.
 */
export interface CreateSessionResponse {
    session_id: string;
    state: "active" | "queued";
    scenario_id?: string;
    language?: string;
    /** Only present when `state === "queued"`. */
    queue_position?: number;
}

export interface ResumeSessionResponse {
    session_id: string;
    state: string;
    scenario_id: string;
    current_clip_id: string;
    /** Number of turns already completed before the resume. */
    turn_count: number;
}

export interface QueueStatusResponse {
    session_id: string;
    state: "queued" | "active";
    queue_position: number | null;
}

// ─── Scenario / Clip ──────────────────────────────────────────────────────────

/**
 * Determines which clip plays next based on the `escalation_score` from the
 * single BehaviourResult produced for the current clip.
 *
 * Conditions are evaluated in order — the first match wins.
 * Together they must cover the full range from -1.0 to 1.0 with no gaps.
 */
export interface BranchCondition {
    /** Inclusive lower bound. */
    min_score: number;
    /** Exclusive upper bound. */
    max_score: number;
    /** ID of the next clip to play, or `null` to end the scenario. */
    next_clip: string | null;
}

/**
 * Metadata for a single clip within a scenario.
 *
 * Passed to the Evaluation container as part of each `AnalysisWindow` so the
 * classifier and LLM have context about what the student is responding to.
 */
export interface ClipMetadata {
    clip_id: string;
    scenario_id: string;
    /** Verbatim transcript of the dialogue in this clip. */
    transcript: string;
    /**
     * Observable behaviors in the clip relevant to de-escalation,
     * e.g. `"raised_voice"`, `"aggressive_posture"`. Used as context by the
     * classifier and LLM. See `scenarios/schema.md` for recommended values.
     */
    notable_features: string[];
    branch_conditions: BranchCondition[];
}

// ─── Evaluation — cross-container requests ───────────────────────────────────

/**
 * A clip-scoped window of captured data covering the student's complete response
 * to one clip. Assembled by ClipSession and dispatched once per clip to the
 * Evaluation container when the Transcription service emits its final segment.
 *
 * Wire format: POST /evaluate/analyse
 */
export interface AnalysisWindow {
    window_id:     WindowID;
    session_id:    string;
    frames:        VideoFrame[];
    /** Flattened MFCCs from all AudioChunks accumulated during the clip. [n_frames][13] */
    mfccs:         MfccMatrix;
    /** Complete transcript of the student's response for this clip. */
    transcript:    string;
    clip_metadata: ClipMetadata;
}

// ─── Evaluation — cross-container results ────────────────────────────────────

/**
 * A summary of the multimodal signals detected in a single analysis window.
 * Produced by the Evaluation container, forwarded to the Feedback container
 * as part of each ConversationTurn.
 */
export interface SignalSummary {
    /** 0.0 (relaxed) to 1.0 (tense). */
    voice_tension: number;
    /** Syllables per second. */
    speech_pace: number;
    /** Average landmark movement per frame. */
    hand_velocity: number;
    /** 0.0 (erratic) to 1.0 (steady). */
    gaze_stability: number;
    /** Ratio of frames where an open palm is detected. */
    open_palm_ratio: number;
    /** Notable signals detected, e.g. `"raised_voice"`, `"stub_mode"`. */
    notable_signals: string[];
}

/**
 * The result of analyzing a clip's complete AnalysisWindow.
 * Produced by the Evaluation container, consumed by the App container
 * (for immediate client branching) and the Feedback container (for debrief).
 */
export interface BehaviourResult {
    window_id: WindowID;
    session_id: string;
    /** -1.0 = strongly de-escalating, 1.0 = strongly escalating. */
    escalation_score: number;
    dominant_emotion: string;
    /** 0.0 to 1.0. */
    confidence: number;
    signal_summary: SignalSummary;
}

// ─── Feedback — cross-container types ────────────────────────────────────────

/**
 * A single turn in the conversation — one clip the student responded to,
 * paired with the behavior analysis of their response.
 *
 * Accumulated by the App container during a session and compiled into a
 * FeedbackRequest at session end.
 */
export interface ConversationTurn {
    turn_id: number;
    clip: ClipMetadata;
    student_response: BehaviourResult;
    student_transcript: string;
}

/**
 * Sent from the App container to the Feedback container at session end.
 * Contains the full conversation history needed to generate a debrief.
 *
 * Wire format: POST /feedback/generate
 */
export interface FeedbackRequest {
    session_id: string;
    scenario_id: string;
    /** ISO 639-1 language code, e.g. `"nl"`. */
    language: string;
    history: ConversationTurn[];
}

// ─── Client-side session state ────────────────────────────────────────────────

/**
 * The client's view of the current session state.
 *
 * Mirrors the server-side state machine defined in `docs/SESSION_LIFECYCLE.md`,
 * with an additional `"idle"` state for before any session has been created.
 */
export type SessionState =
    | "idle"
    | "connecting"
    | "queued"
    | "active"
    | "paused"
    | "completed"
    | "dropped"
    | "error";